// Authoritative Coach to RM Mapping generated from Coaches Schedule - Weekdays.csv & Weekend.csv
export const COACH_TO_RM_MAP: Record<string, string> = {
  "Aafrin Deshmukh": "Vedant Kamble",
  "Aarti Thakur": "Ganeshchandar",
  "Abhilasha Jha": "Sana Choudhary",
  "Abhishek Balkrishna Deshpande": "Nazeer Basha",
  "Abhishek Charudatta Patil": "Shailendra Waingankar",
  "Abhishek Jaiswal": "Mohit Patel",
  "Aditya Singh": "Pushpak Kawoor",
  "Akash Thomas Robert": "Deepak Yadav",
  "Akshay Halagannavar": "Vedant Kamble",
  "Alok Nandlal Vishwkarma": "Presley Dsouza",
  "Amarjit Singh": "Prem Thakur",
  "Ambarish Sharma": "Presley Dsouza",
  "Amitava Chakraborty": "Navdeepkaur Bagal",
  "Amlan Mahanta": "Akshay Kesarwani",
  "Amogh Vajandar": "NA",
  "Anand Roy": "Anil Mishra",
  "Aniket Biswas": "Deepak Yadav",
  "Anjali Krishnan": "Pushpak Kawoor",
  "Ankit Arora": "Presley Dsouza",
  "Ankit Kumar Singh": "Nazeer Basha",
  "Ankit Sen": "Deepak Yadav(Temp - KA)",
  "Ankush Raj": "Anil Mishra",
  "Anshu Mondal": "Dharmika Sonawane",
  "Ansuman Samal": "Anil Mishra",
  "Anukarssa Dutta": "Nikhil Singh",
  "Anush Nandan Rao": "Pushpak Kawoor",
  "Anushuya Gururajan": "Radhika Dadrekar",
  "Anustoop Biswas": "Syed Shajahan",
  "Arbina Ansari": "Presley Dsouza",
  "Arjun Singh Rawat": "Sana Choudhary",
  "Arka Datta Chaudhuri": "Anil Mishra",
  "Arnab Karfa": "Pushpak Kawoor",
  "Arprita Bank": "Shailendra Waigankar",
  "Arulsaravanan S": "Anil Mishra",
  "Arvind Tayade": "NA",
  "Ashi Gagoria": "Radhika Dadrekar",
  "Ashirwad Swain": "Nikhil Mehra",
  "Ashish Pattnaik": "Nazeer Basha",
  "Ashutosh Verma": "NA",
  "Avek Harayan": "Nikhil Singh",
  "B Renuga Devi": "Mohit Patel",
  "Basant Khandelwal": "NA",
  "Bhairavi Gadhvi": "Nazeer Basha (Temp - VN)",
  "Bhanu Naga Sai Siva Ram Jami": "Anil Mishra",
  "Bhavya Saini": "Akshay Kesarwani",
  "Bhawesh Pandiyar": "Nikhil Singh",
  "Biplab Kar": "Anil Mishra",
  "Chanchal Chawla": "Radhika Dadrekar",
  "Chinmay Kelaskar": "Priya Narayan",
  "Chirag Babulal Satkar": "Pushpak Kawoor",
  "Chirag G": "Presley Dsouza",
  "Damekar Priyanka Shriram": "Navdeepkaur Bagal",
  "Debalina Kundu": "Anil Mishra",
  "Debangi Chouhan": "Presley Dsouza",
  "Debanjan Sasmal": "Presley Dsouza",
  "Devika Sushilkumar Raul": "Deepak Yadav",
  "Dhairya Waghela": "Nikhil Mehra",
  "Dhanashri Kadam": "Navdeepkaur Bagal",
  "Dhanumuri Jishitha": "Mohit Patel",
  "Dhruva Kumar K B": "Radhika Dadrekar",
  "Dipayan Das": "Prem Thakur",
  "Divanshu Jain": "Nikhil Singh",
  "Durgesh Dhananjay Patil": "Anil Mishra",
  "Ganesh Bhiku Bhilare": "Nikhil Mehra",
  "Gautam Rohidas Tari": "Pushpak Kawoor",
  "Gipolson Pahsyntiew": "Nikhil Mehra",
  "Gourav Nigam": "Pushpak Kawoor",
  "Gundhudi Viswa Teja": "Nazeer Basha",
  "Guru Sabari TS": "Pushpak Kawoor",
  "Gurunath Pai": "Navdeepkaur Bagal",
  "H S Dhanush": "Pushpak Kawoor",
  "Harsh Ghag": "Prem Thakur",
  "Harsh Seth": "Shailendra Waingankar",
  "Hrdyansh Pandey": "Nazeer Basha",
  "Ifthikar Ahammad Shaik": "Syed Shajahan",
  "Isha Agarwal": "Prem Thakur",
  "Jenny Gogoi": "Jay Vyas",
  "Jitendra Patil": "Ganeshchandar",
  "Joyjeet Bose": "Anil Mishra",
  "Karthick Raja.J": "Ganeshchandar",
  "Kasthoori Mahalingam K": "Deepak Yadav",
  "Kedar Dashrath Morvekar": "Priya Narayan",
  "Ketan Ghanshyam Amrute": "Domnic Dsouza",
  "Kiran R Khande": "Sana Choudhary",
  "Kotyada Shashank": "Domnic Dsouza",
  "Krishna Shantilal Chourasiya": "Domnic Dsouza",
  "Kunal Pawar": "Anthony John",
  "Kathiravan M": "Shankar Nagdev",
  "Madabushi Abhirami": "Nikhil Singh",
  "Mahendra Singh Rathore": "Shailendra Waingankar",
  "Mani K": "Prem Thakur",
  "Manishankar Pandey": "Presley Dsouza",
  "Manoj Chowgule": "Deepak Yadav",
  "Maruti Kasture": "Rohini Pednekar",
  "Mayank Ratgali": "Mohit Patel",
  "Mayank Manikam": "Prem Thakur",
  "Md Minhajul Haque": "Shankar Nagdev",
  "Mehendi Sil": "Nikhil Singh",
  "Melwyn Cardoza": "Deepak Yadav",
  "Michelle Joaquim Fernandes": "Radhika Dadrekar",
  "Mohammad Arafat Akhtar": "Deepak Yadav(Temp - KA)",
  "Saif Shaikh": "Sana Choudhary",
  "Mohanapraba R B": "Pushpak Kawoor",
  "Molai Patra": "Nikhil Mehra",
  "Moniga C": "Deepak Yadav",
  "N Bala Bhargav": "Nikhil Singh",
  "Nagathilak U": "Pushpak Kawoor",
  "Narendar Mudaliyar": "Presley Dsouza",
  "Neeraj Gupta": "Navdeepkaur Bagal",
  "Neha Nupur": "Nikhil Singh",
  "Nikhil Gaikwad": "Shubham Sharma",
  "Nikita Tiwari": "NA",
  "Nilesh Prabhakar Salvi": "Anil Mishra",
  "Nilesh Tejaram Mali": "Presley Dsouza",
  "Niranjan Sharad Kurhe": "Jay Vyas",
  "Nischay Sharma": "Dharmika Sonawane",
  "Om Prabhakar Rai": "Nikhil Mehra",
  "Omkar Deshpande": "Nikhil Singh",
  "Omkar Vishwas Gaikwad": "Mohit Patel",
  "Padma T Mattihalli": "Navdeepkaur Bagal",
  "Pankit Mota": "Vedant Kamble",
  "Parnavi Jiwaji Rane": "Anil Mishra",
  "Patwardhan Vaibhav Prakash": "Syed Shajahan",
  "Payal Kedia": "Shankar Nagdev",
  "Piyush Mishra": "Mohit Patel",
  "Piyush Manuja": "NA",
  "Prachi Gusain": "Navdeepkaur Bagal",
  "Pragati Mazumder": "Domnic Dsouza",
  "Prakhar Dhyani": "Syed Shajahan",
  "Pranab Maity": "Jay Vyas",
  "Pranali Shashidhar Patil": "Rohini Pednekar",
  "Pranjal Prashant Revankar": "Nikhil Singh",
  "Prasad Harendra Sureshprasad": "Dharmika Sonawane",
  "Prathamesh Vinay Baraskar": "Syed Shajahan",
  "Pratik Gengaje": "Vedant Kamble",
  "Pratik Dubey": "Ganeshchandar",
  "Pratik Patil": "Ganeshchandar(Temp - KA)",
  "Pratik Gaitonde": "Vedant Kamble",
  "Pratish Raj": "Vicky Gaikwad",
  "Prince Kumar": "Nikhil Singh",
  "Prince Wilson Lobo": "Mohit Patel",
  "Priya Khemani": "Nikhil Mehra",
  "Priya Nevis Miranda": "Domnic Dsouza",
  "Priyanka Kumari": "Nazeer Basha",
  "Priyanka Nag": "Akshay Kesarwani",
  "Priyasivadharshini T N": "Rohini Pednekar",
  "Purushothaman Thirumalai": "Shankar Nagdev",
  "Rahul Keshaorao Kapse": "Pushpak Kawoor",
  "Rahul Rajan Pawar": "Presley Dsouza",
  "Rahul Jagtap": "Nikhil Singh",
  "Raj Bali": "Akshay Kesarwani",
  "Rajdeep Das": "Pushpak Kawoor",
  "Rakshan M": "Shankar Nagdev",
  "Rayala Siva Naga Ratna Rao": "Mohit Patel",
  "Rishi R": "Nikhil Mehra",
  "Rishija Shrivas": "Anil Mishra",
  "Ritik Rai": "Dharmika Sonawane",
  "Rohit S": "Mohit Patel",
  "Rohit Dey": "Nikhil Singh",
  "Rohit Bhagwat": "Ganeshchandar",
  "Rohit Sharma": "Presley Dsouza",
  "Rohit Mokashi": "Radhika Dadrekar",
  "Ronanki Kiran Kumar": "Vicky Gaikwad",
  "Rupak Kumar": "Nikhil Mehra",
  "Badrinath S": "Nikhil Mehra",
  "S Ezhilarasi": "Nikhil Mehra",
  "Rohitvassan S": "Shailendra Waingankar(Temp - KA)",
  "S Senthil Nagarajan": "Priya Narayan",
  "Pooja S": "Mohit Patel",
  "Sachin Kalher": "Rohini Pednekar",
  "Sachin Patil": "Ganeshchandar",
  "Sahana P S": "Anthony John",
  "Sahas Nilesh Narkar": "Syed Shajahan",
  "Sairaj Chittal": "Nikhil Mehra",
  "Sakshi Bhikaro Naik Gaonkar": "Pushpak Kawoor",
  "Samhitha Sharma B S": "Jay Vyas",
  "Samip Roy": "Nikhil Mehra",
  "Samta Sharma": "Nazeer Basha",
  "Sangharsh Karpe": "Dharmika Sonawane",
  "Sanjana P": "Anthony John",
  "Sanjeev Ramashankar Mishra": "Vedant Kamble",
  "Sanjeev Nair": "Prem Thakur",
  "Sanket N B": "Pushpak Kawoor",
  "Sanvi Bhikaro Naik Gaonkar": "Jay Vyas",
  "Saranya Y": "Priya Narayan",
  "Sarvar Subair Khan": "Anil Mishra",
  "Satakshi Shorya": "Ganeshchandar",
  "Sathyan P M": "Nikhil Singh",
  "Satish Kumar": "Deepak Yadav(Temp - KA)",
  "Satyam Srivastav": "Nikhil Singh",
  "Saurabh Jain": "Nazeer Basha (Temp - VN)",
  "Sayantan Chandra": "Prem Thakur",
  "Shaik Abdul Kalam": "Vicky Gaikwad",
  "Shaista Parveen": "Nazeer Basha (Temp - VN)",
  "Irfan Sheik": "Presley Dsouza",
  "Shiva Kumar Arikilla": "Radhika Dadrekar",
  "Shivam Sirsikar": "Shubham Sharma",
  "Shivansh Tiwari": "Shailendra Waingankar",
  "Shouvik Kar": "Presley Dsouza",
  "Shravani Arun Patil": "Anil Mishra",
  "Shreyash Karkare": "Shailendra Waingankar",
  "Shrutarshi Ray": "Syed Shajahan",
  "Shubham Kumthekar": "Shankar Nagdev",
  "Shubham Srivastava": "Priya Narayan",
  "Shubham Gaitonde": "Sana Choudhary",
  "Siddharthan S": "Pushpak Kawoor",
  "Skanda Bhargava K B": "Syed Shajahan",
  "Smaraki Mohanty": "Vedant Kamble",
  "Soham Anant Khasbardar": "Anil Mishra",
  "Soham Devdatta Rumde": "Anil Mishra",
  "Soham Pavan Shirode": "Vicky Gaikwad",
  "Soumalya Mondal": "Anil Mishra",
  "Soumik Biswas": "Vicky Gaikwad",
  "Sreejit Sreedharan": "Dharmika",
  "Subhabrata Roy": "Anil Mishra",
  "Subhapratha M": "Priya Narayan",
  "Subrat Panigrahi": "Mohit Patel",
  "Subrata Das": "Syed Shajahan",
  "Sujal Verma": "Anil Mishra",
  "Sujay Mondal": "Shailendra Waigankar",
  "Sujit Rakesh Shukla": "Syed Shajahan",
  "Sumeet Chowgule": "Vedant Kamble",
  "Sunny": "Mohit Patel",
  "Suryatra Chakraborty": "Pushpak Kawoor",
  "Suvankar Maity": "Mohit Patel",
  "Suyash Sharma": "Presley Dsouza",
  "Swapnil Bansod": "Deepak Yadav",
  "Swarada Chandrashekhar Upadhye": "Shankar Nagdev",
  "Swathi Shetty": "Anthony John",
  "Tamizhanban N": "Pushpak Kawoor",
  "Rajan R": "Sana Choudhary",
  "Trupti Prabhu": "Ganeshchandar",
  "Vaibhav Dubey": "Pushpak Kawoor",
  "Vaishnav Vijay Padwal": "Deepak Yadav(Temp - KA)",
  "Vaishnavi": "Priya Narayan",
  "Vatsal Shah": "Sana Choudhary",
  "Vigneshwaran S": "Nikhil Singh",
  "Vijay Chauhan": "Rohini Yadav",
  "Vijay Pareek": "Deepak Yadav",
  "Vinanti Ramtarya": "Rohini Pednekar",
  "Vishal Sancheria": "Anthony John",
  "Vishal Gangwal": "Nikhil Mehra",
  "Vishwadeep Jadhav": "Vicky Gaikwad",
  "Vivek Kumar Singh": "Dharmika Sonawane",
  "Vivek Mehto": "Pushpak Kawoor",
  "Vivek Chavan": "Radhika Dadrekar",
  "Vivek Tayade": "Vicky Gaikwad",
  "Vivek Surendrakumar Mishra": "Vicky Gaikwad",
  "Yash Meena": "Presley Dsouza",
  "Yash Tulapurkar": "Jay Vyas",
  "Yasmin": "Shubham Sharma",
  "Yogesh Ganu": "Shailendra Waingankar",
  "Arnab karfa": "Presley Dsouza",
  "Kalpesh Pednekar": "Deepak Yadav"
};
