import type { SameDayDemoRequest } from './types';

export const INITIAL_SAME_DAY_DEMO_REQUESTS: SameDayDemoRequest[] = [
  {
    id: 'sdd-1',
    srn_no: 'SRN115408',
    demo_date: '2025-05-02',
    student_name: 'Advik Tripathi',
    sales_person_name: 'Jeenal',
    country_name: 'India',
    slot_requested: '6-8pm',
    sales_remark: 'good friendly interactive coach',
    sales_confirmation: 'Pending',
    demo_status: 'Pending',
    created_at: '2025-05-02T10:15:00Z'
  },
  {
    id: 'sdd-2',
    srn_no: 'SRN115431',
    demo_date: '2025-05-02',
    student_name: 'Rimphy',
    sales_person_name: 'Iwin',
    country_name: 'USA',
    slot_requested: '09:00',
    sales_remark: 'urgent morning demo request',
    sales_confirmation: 'Pending',
    demo_status: 'Pending',
    created_at: '2025-05-02T10:20:00Z'
  },
  {
    id: 'sdd-3',
    srn_no: 'SRN115156',
    demo_date: '2025-05-01',
    student_name: 'Aaryan',
    sales_person_name: 'Azam',
    country_name: 'USA',
    slot_requested: '5.10am',
    sales_remark: 'chess.com 1200, need sr. coach.',
    sales_confirmation: 'Pending',
    demo_status: 'Pending',
    created_at: '2025-05-01T08:30:00Z'
  },
  {
    id: 'sdd-4',
    srn_no: 'SRN115377',
    demo_date: '2025-04-30',
    student_name: 'Catherine',
    sales_person_name: 'Mahesh',
    country_name: 'USA',
    slot_requested: '02:15-3:25',
    sales_confirmation: 'Pending',
    demo_status: 'Pending',
    created_at: '2025-04-30T11:00:00Z'
  },
  {
    id: 'sdd-5',
    srn_no: 'SRN115394',
    demo_date: '2025-04-30',
    student_name: 'Smita Panigrahi',
    sales_person_name: 'Samritha',
    country_name: 'India',
    slot_requested: '5pm to 6pm',
    sales_remark: 'ITP coach',
    sales_confirmation: 'Pending',
    demo_status: 'Pending',
    created_at: '2025-04-30T12:15:00Z'
  },
  {
    id: 'sdd-6',
    srn_no: 'SRN115402',
    demo_date: '2025-04-30',
    student_name: 'Akanasha & Aakriti',
    sales_person_name: 'Jeenal',
    country_name: 'India',
    slot_requested: '20:00 pm',
    sales_remark: '2 kids, good friendly interactive',
    sales_confirmation: 'Pending',
    demo_status: 'Pending',
    created_at: '2025-04-30T13:45:00Z'
  },
  {
    id: 'sdd-7',
    srn_no: 'SRN115369',
    demo_date: '2025-04-29',
    student_name: 'Mousa',
    sales_person_name: 'Akshay',
    country_name: 'Other Countries',
    slot_requested: '9-10PM',
    sales_remark: 'Senior level coaching requested',
    coach_preference: 'Excellent Coach',
    sales_confirmation: 'Confirm',
    slot_allotted: '21:10',
    coach_assigned_name: 'Mayank Chandra Ratgali',
    demo_status: 'Assigned on Portal',
    operations_remark: 'Assigned on portal',
    created_at: '2025-04-29T15:00:00Z'
  },
  {
    id: 'sdd-8',
    srn_no: 'SRN115404',
    demo_date: '2025-04-29',
    student_name: 'Arnav',
    sales_person_name: 'Smriti',
    country_name: 'India',
    slot_requested: '11 to 12:30 PM',
    sales_remark: 'good friendly interactive',
    sales_confirmation: 'Confirm',
    slot_allotted: '11:25',
    coach_assigned_name: 'Suman Thapa',
    demo_status: 'Not Update on portal',
    operations_remark: 'Pending portal sync',
    created_at: '2025-04-29T10:15:00Z'
  },
  {
    id: 'sdd-9',
    srn_no: 'SRN115413',
    demo_date: '2025-04-29',
    student_name: 'Vivaan',
    sales_person_name: 'Samritha',
    country_name: 'India',
    slot_requested: '3pm to 4pm',
    sales_remark: 'ITP coach',
    sales_confirmation: 'Confirm',
    slot_allotted: '15:55',
    coach_assigned_name: 'Vatsal Shah',
    demo_status: 'Assigned on Portal',
    operations_remark: 'Assigned on portal',
    created_at: '2025-04-29T12:00:00Z'
  },
  {
    id: 'sdd-10',
    srn_no: 'SRN115414',
    demo_no: 'Demo-71559',
    demo_date: '2025-04-29',
    student_name: 'Smriti',
    sales_person_name: 'Smriti',
    country_name: 'India',
    slot_requested: '7 to 8:30 PM IST',
    sales_remark: 'Good Friendly coach',
    sales_confirmation: 'Confirm',
    slot_allotted: '19:30',
    coach_assigned_name: 'Yogesh Arvind Ganu',
    demo_status: 'Assigned on Portal',
    operations_remark: 'Assigned on portal',
    created_at: '2025-04-29T14:30:00Z'
  },
  {
    id: 'sdd-11',
    srn_no: 'SRN115428',
    demo_date: '2025-04-29',
    student_name: 'Ashrapov Diyor',
    sales_person_name: 'Kinjal',
    country_name: 'UK',
    slot_requested: '9.30pm',
    sales_remark: 'Demo with coach who will take classes',
    coach_preference: 'Tushar S',
    sales_confirmation: 'Confirm',
    slot_allotted: '21:30',
    coach_assigned_name: 'Tushar Saraswat',
    demo_status: 'Assigned on Portal',
    operations_remark: 'Assigned on portal',
    created_at: '2025-04-29T16:00:00Z'
  },
  {
    id: 'sdd-12',
    srn_no: 'SRN115444',
    demo_no: 'Demo-71617',
    demo_date: '2025-04-29',
    student_name: 'Jayesh Lead',
    sales_person_name: 'Jayesh',
    country_name: 'India',
    slot_requested: '7 PM to 8 PM',
    sales_remark: 'Adult lead',
    coach_preference: 'Good Friendly & Interactive coach',
    sales_confirmation: 'Confirm',
    slot_allotted: '19:55',
    coach_assigned_name: 'Yogesh Arvind Ganu',
    demo_status: 'Assigned on Portal',
    operations_remark: 'Assigned on portal',
    created_at: '2025-04-29T16:15:00Z'
  }
];
